
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action undoBtn;
	
	private global::Gtk.Action redoBtn;
	
	private global::Gtk.Action deleteBtn;
	
	private global::Gtk.ToggleAction drawBtn;
	
	private global::Gtk.ToggleAction moveBtn;
	
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Toolbar editorToolbar;
	
	private global::Gtk.DrawingArea drawingarea1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.undoBtn = new global::Gtk.Action ("undoBtn", null, null, "gtk-go-back");
		w1.Add (this.undoBtn, null);
		this.redoBtn = new global::Gtk.Action ("redoBtn", null, null, "gtk-go-forward");
		w1.Add (this.redoBtn, null);
		this.deleteBtn = new global::Gtk.Action ("deleteBtn", null, null, "gtk-close");
		w1.Add (this.deleteBtn, null);
		this.drawBtn = new global::Gtk.ToggleAction ("drawBtn", null, null, "gtk-edit");
		w1.Add (this.drawBtn, null);
		this.moveBtn = new global::Gtk.ToggleAction ("moveBtn", null, null, "gtk-index");
		w1.Add (this.moveBtn, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("GraphicsEditor");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='editorToolbar'><toolitem name='undoBtn' action='undoBtn'/><toolitem name='redoBtn' action='redoBtn'/><toolitem name='deleteBtn' action='deleteBtn'/><toolitem name='drawBtn' action='drawBtn'/><toolitem name='moveBtn' action='moveBtn'/></toolbar></ui>");
		this.editorToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/editorToolbar")));
		this.editorToolbar.Name = "editorToolbar";
		this.editorToolbar.ShowArrow = false;
		this.fixed1.Add (this.editorToolbar);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.editorToolbar]));
		w2.X = 4;
		w2.Y = 4;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.drawingarea1 = new global::Gtk.DrawingArea ();
		this.drawingarea1.WidthRequest = 600;
		this.drawingarea1.HeightRequest = 400;
		this.drawingarea1.Name = "drawingarea1";
		this.fixed1.Add (this.drawingarea1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.drawingarea1]));
		w3.X = 12;
		w3.Y = 58;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 625;
		this.DefaultHeight = 472;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
